export const ObjectListing = {
  Location: {
    "# Operation *": "ADD",
    "Object *": "Location",
    "dcTrack Location Code*": "",
    "dcTrack Location Name*": "",
    "dcTrack Location Hierarchy*": "",
    "dcTrack Location Parent": "",
    "Can Contain Assets": "",
    "Data Center Area*": "",
    "Country*": "",
    "Enable AC Virtual Power Chain": "",
    "Enable DC Virtual Power Chain": "",
    "Is Default Location": "",
    "Capacity(kW)": "",
  },
  Cabinet: {
    "# Operation *": "ADD",
    "Object *": "Cabinet",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    Status: "Planned",
    "Front Faces": "",
    "Aisle Label": "",
    "Row Label **": "",
    "Position in Row **": "",
    "Power Capacity (kW)": "",
    "Weight Capacity": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "COOLING UNIT": {
    "# Operation *": "ADD",
    "Object *": "COOLING UNIT",
    "Name*": "",
    "Make*": "",
    "Model*": "",
    "Part Number": "",
    "Location*": "",
    "Location Name": "",
    Status: "Planned",
    "Cooling Zone": "",
    "Cooling Zone Redundancy": "",
    "Sensible Capacity (Tons)": "",
    "Sensible Capacity (kW)": "",
    "Airflow Rate (cfm)": "",
    "Compensation Factor": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DATA PANEL-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "DATA PANEL-RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DEVICE-BLADE": {
    "# Operation *": "ADD",
    "Object *": "Device Blade",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    Status: "Planned",
    "Chassis **": "",
    "Chassis Face **": "",
    "Slot Position **": "",
    "Is VM Host": "",
    "VM Cluster": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DEVICE-BLADE CHASSIS-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "DEVICE-BLADE CHASSIS-RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "Device-Free Standing": {
    "# Operation *": "ADD",
    "Object *": "Device Free Standing",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    Status: "Planned",
    "Front Faces": "",
    "Aisle Label": "",
    "Row Label **": "",
    "Position in Row **": "",
    "Power Capacity (kW)": "",
    "Weight Capacity": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "Network-Free Standing": {
    "# Operation *": "ADD",
    "Object *": "Device Free Standing",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    Status: "Planned",
    "Front Faces": "",
    "Aisle Label": "",
    "Row Label **": "",
    "Position in Row **": "",
    "Power Capacity (kW)": "",
    "Weight Capacity": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DEVICE-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Device Non Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "COOLING ZONE": {
    "# Operation *": "ADD",
    "Object *": "COOLING ZONE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DATA PANEL-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "DATA PANEL-NON RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "INVERTER-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "INVERTER-NON RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "PROBE-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "PROBE-NON RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "DEVICE-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Device Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "RACK UPS-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "RACK UPS-RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "NETWORK-BLADE": {
    "# Operation *": "ADD",
    "Object *": "Network Blade",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    Status: "Planned",
    "Chassis **": "",
    "Chassis Face **": "",
    "Slot Position **": "",
    "Is VM Host": "",
    "VM Cluster": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "NETWORK-CHASSIS-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Network Chassis Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    Status: "Planned",
    "Chassis **": "",
    "Chassis Face **": "",
    "Slot Position **": "",
    "Is VM Host": "",
    "VM Cluster": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "NETWORK-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Network Non Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "NETWORK-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Network Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  PASSIVE: {
    "# Operation *": "ADD",
    "Object *": "Passive",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "PROBE-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Probe Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "RACK PDU-NON RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Rack PDU Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "RACK PDU-ZERO U": {
    "# Operation *": "ADD",
    "Object *": "Rack PDU Zero U",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    Status: "Planned",
    "Depth Position **": "",
    "Cabinet Side **": "",
    "IP Address": "",
    "IP Address Port Name": "",
    "SNMP Write Community String": "",
    "User Name": "",
    Password: "",
    Notes: "",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  "TRANSFORMER-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Transformer Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    Status: "Planned",
    "Asset Tag": "",
    "Installation Date": "",
    "Serial Number": "",
    RUHeight: "",
  },
  UPS: {
    "# Operation *": "ADD",
    "Object *": "UPS",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    Status: "Planned",
    "Asset Tag": "",
    "Rating (kVA)": "",
    "Rating (kW)": "",
    "Rating (Vac)": "",
    "Output Wiring": "",
    "Power Fed From (Inlet)": "",
    "Source (Inlet)": "",
    "Source Location (Inlet)": "",
    "Power Fed From (Bypass)": "",
    "Source (Bypass)": "",
    "Source Location (Bypass)": "",
  },
  "TRANSFORMER-FREE STANDING": {
    "# Operation *": "ADD",
    "Object *": "TRANSFORMER-FREE STANDING",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    Status: "Planned",
    "Asset Tag": "",
    "Rating (kVA)": "",
    "Phase Volts": "",
    "Wire Gauge": "",
    "Power Fed From": "",
    Source: "",
    "Source Location": "",
  },
  "POWER PANEL-FREE STANDING": {
    "# Operation *": "ADD",
    "Object *": "POWER PANEL-FREE STANDING",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    Status: "Planned",
    "Asset Tag": "",
    "Wire Colors": "",
    "Rating (A)": "",
    "No of Poles": "",
    "Panel Layout": "",
    "Pole Numbering": "",
    "First Pole Number": "",
    "Power Fed From": "",
    Source: "",
    "Source Location": "",
  },
  "UPS Bank": {
    "# Operation *": "ADD",
    "Object *": "UPS Bank",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    Status: "Planned",
    "Asset Tag": "",
    "Rating (Vac)": "",
    "Rating (A)": "",
    "Output Wiring": "",
    "UPS Bank Redundancy": "",
  },
  SWITCH: {
    "# Operation *": "ADD",
    "Object *": "SWITCH",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    Status: "Planned",
    "Asset Tag": "",
    "Rating (Vac)": "",
    "Rating (A)": "",
    "Output Wiring": "",
  },
  "POWER OUTLET": {
    "# Operation *": "ADD",
    "Object *": "POWER OUTLET",
    "Make *": "",
    "Model *": "",
    "Name *": "",
    "Location *": "",
    "Aisle Label **": "",
    "Row Label **": "",
    "Position in Row **": "",
    "Cabinet **": "",
    "U Position **": "",
    Status: "Planned",
    "Asset Tag": "",
  },
  "POWER OUTLET-BUSWAY": {
    "# Operation *": "ADD",
    "Object *": "POWER OUTLET-BUSWAY",
    "Make *": "",
    "Model *": "",
    "Name *": "",
    "Location *": "",
    "Busway *": "",
    "Position in Row **": "",
    "Cabinet **": "",
    "U Position **": "",
    Status: "Planned",
    "Asset Tag": "",
  },
  "LOAD DEVICE": {
    "# Operation *": "ADD",
    "Object *": "LOAD DEVICE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Switch or UPS Bank": "",
    Status: "Planned",
    "Asset Tag": "",
    "Device Number": "",
    "Rating (A)": "",
    "Preferred State": "",
    "Active State": "",
    "I.C Rating (kA)": "",
    "Wire Gauge": "",
    "AC Bay": "",
    "Line Side": "",
    "Power Fed From": "",
    Source: "",
    "Source Location": "",
    "Load Side": "",
  },
  "INVERTER-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "Inverter Rackable",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    "SNMP Write Community String": "",
    "User Name": "",
    Password: "",
    Status: "Planned",
    "Asset Tag": "",
  },
  "HEAT REJECTION": {
    "# Operation *": "ADD",
    "Object *": "HEAT REJECTION",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    Status: "Planned",
    "Asset Tag": "",
    "Location *": "",
    "Location Name": "",
  },
  "Floor PDU": {
    "# Operation *": "ADD",
    "Object *": "Floor PDU",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    Status: "Planned",
    "Asset Tag": "",
    "Location *": "",
    "Location Name": "",
  },
  "FAP-RACKABLE": {
    "# Operation *": "ADD",
    "Object *": "FAP-RACKABLE",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location *": "",
    "Location Name": "",
    "Cabinet **": "",
    "U Position **": "",
    "Rails Used **": "",
    "Orientation **": "",
    "SNMP Write Community String": "",
    "User Name": "",
    Password: "",
    Status: "Planned",
    "Asset Tag": "",
  },
};

const Translate = {
  "COOLING UNIT": "COOLING UNIT", //
  "COOLING ZONE": "COOLING ZONE", //
  Cabinet: "Cabinet", //
  "DATA PANEL-NON RACKABLE": "DATA PANEL-NON RACKABLE",
  "DATA PANEL-RACKABLE": "DATA PANEL-RACKABLE", //
  "DATA PANEL-ZERO U": "RACK PDU-ZERO U", //
  "DEVICE-BLADE": "DEVICE-BLADE", //
  "DEVICE-BLADE CHASSIS-RACKABLE": "DEVICE-BLADE CHASSIS-RACKABLE", //
  "DEVICE-NON RACKABLE": "DEVICE-NON RACKABLE", //
  "DEVICE-RACKABLE": "DEVICE-RACKABLE", //
  "Device-Free Standing": "Device-Free Standing", //
  "FAP-RACKABLE": "FAP-RACKABLE", //
  "Floor PDU": "Floor PDU", //
  "HEAT REJECTION": "HEAT REJECTION", //
  "INVERTER-NON-RACKABLE": "INVERTER-NON RACKABLE", //
  "INVERTER-RACKABLE": "INVERTER-RACKABLE", //
  "LOAD DEVICE": "LOAD DEVICE", //
  "NETWORK-BLADE": "NETWORK-BLADE", //
  "NETWORK-CHASSIS-RACKABLE": "NETWORK-CHASSIS-RACKABLE", //
  "NETWORK-NON RACKABLE": "NETWORK-NON RACKABLE", //
  "NETWORK-RACKABLE": "NETWORK-RACKABLE", //
  "Network-Free Standing": "Network-Free Standing", //
  PASSIVE: "PASSIVE", //
  "POWER OUTLET": "POWER OUTLET", //
  "POWER OUTLET-BUSWAY": "POWER OUTLET-BUSWAY", //
  "PROBE-NON RACKABLE": "PROBE-NON RACKABLE", //
  "PROBE-RACKABLE": "PROBE-RACKABLE", //
  "RACK PDU-NON RACKABLE": "RACK PDU-NON RACKABLE", //
  "RACK PDU-RACKABLE": "DEVICE-RACKABLE",
  "RACK PDU-ZERO U": "RACK PDU-ZERO U", //
  "RACK UPS-RACKABLE": "RACK UPS-RACKABLEE", //
  SWITCH: "SWITCH", //
  "TRANSFORMER-FREE STANDING": "TRANSFORMER-FREE STANDING", //
  "TRANSFORMER-RACKABLE": "TRANSFORMER-RACKABLE", //
  UPS: "UPS", //
  "UPS BANK": "UPS Bank", //
  "Asset Tag": "Asset Tag",
};

// export const UniqueOrder = [
//   "# Operation *",
//   "Object *",
//   "Name *",
//   "Make *",
//   "Model *",
//   "RUHeight",
//   "Part Number",
//   "Location  *",
//   "Location Name",
//   "Cabinet **",
//   "U Position **",
//   "Rails Used **",
//   "Orientation **",
//   "Status",
//   "Notes",
//   "Installation Date",
//   "Serial Number",
//   "Front Faces",
//   "Aisle Label",
//   "Row Label **",
//   "Position in Row **",
//   "Power Capacity (kW)",
//   "Weight Capacity",
//   "Chassis **",
//   "Chassis Face **",
//   "Slot Position **",
//   "Is VM Host",
//   "VM Cluster",
//   "Depth Position **",
//   "Cabinet Side **",
//   "IP Address",
//   "IP Address Port Name",
//   "SNMP Write Community String",
//   "User Name",
//   "Password",
//   "RUHeight",
//   "dcTrack Location Code*",
//   "dcTrack Location Name*",
//   "dcTrack Location Hierarchy*",
//   "dcTrack Location Parent",
//   "Can Contain Assets",
//   "Data Center Area*",
//   "Country*",
//   "Enable AC Virtual Power Chain",
//   "Enable DC Virtual Power Chain",
//   "Is Default Location",
//   "Capacity(kW)",
// ];

export const UniqueOrder = [
  "# Operation *",
  "Object *",
  "dcTrack Location Code*",
  "dcTrack Location Name*",
  "dcTrack Location Hierarchy*",
  "dcTrack Location Parent",
  "Can Contain Assets",
  "Data Center Area*",
  "Country*",
  "Enable AC Virtual Power Chain",
  "Enable DC Virtual Power Chain",
  "Is Default Location",
  "Capacity(kW)",
  "Name *",
  "Make *",
  "Model *",
  "Part Number",
  "Asset Tag",
  "Location *",
  "Location Name",
  "Status",
  "Front Faces",
  "Aisle Label",
  "Row Label **",
  "Position in Row **",
  "Power Capacity (kW)",
  "Weight Capacity",
  "Notes",
  "Installation Date",
  "Serial Number",
  "RUHeight",
  "Name*",
  "Make*",
  "Model*",
  "Location*",
  "Cooling Zone",
  "Cooling Zone Redundancy",
  "Sensible Capacity (Tons)",
  "Sensible Capacity (kW)",
  "Airflow Rate (cfm)",
  "Compensation Factor",
  "Cabinet **",
  "U Position **",
  "Rails Used **",
  "Orientation **",
  "Chassis **",
  "Chassis Face **",
  "Slot Position **",
  "Is VM Host",
  "VM Cluster",
  "Depth Position **",
  "Cabinet Side **",
  "IP Address",
  "IP Address Port Name",
  "SNMP Write Community String",
  "User Name",
  "Password",
  "Rating (kVA)",
  "Rating (kW)",
  "Rating (Vac)",
  "Output Wiring",
  "Power Fed From (Inlet)",
  "Source (Inlet)",
  "Source Location (Inlet)",
  "Power Fed From (Bypass)",
  "Source (Bypass)",
  "Source Location (Bypass)",
  "Phase Volts",
  "Wire Gauge",
  "Power Fed From",
  "Source",
  "Source Location",
  "Wire Colors",
  "Rating (A)",
  "No of Poles",
  "Panel Layout",
  "Pole Numbering",
  "First Pole Number",
  "UPS Bank Redundancy",
  "Aisle Label **",
  "Busway *",
  "Switch or UPS Bank",
  "Device Number",
  "Preferred State",
  "Active State",
  "I.C Rating (kA)",
  "AC Bay",
  "Line Side",
  "Load Side",
];

export const NewModel = {
  Object: "",
  Make: "",
  "Model Name": "",
  "Part Number": "",
  Description: "",
  "Made in": "",
  "Warranty Period": "",
  // Class: "",
  // Subclass: "",
  // Mounting: "",
  // "Form Factor": "",
  "Rack Units": "",
  Height: "",
  Width: "",
  Depth: "",
  Weight: "",
  Units: "",
  DataPortsCount: "",
  PowerPortsCount: "",
  FrontSlotsCount: "",
  BackSlotsCount: "",
  "Do Not Update": "",
  "My Company Standard": "",
  "Front Image File Included": "",
  "Back Image File Included": "",
  Notes: "",
};
