export const BlankCurrentLocation = {
  Location: 0,
  Active: 0,
  Cabinet: 0,
  Asset: 0,
  Counts: {
    Cabinets: 0,
    "Rackable Assets": 0,
    "NonRackable Assets": 0,
  },
  AllItems: {},
  HoldItem: {},
  AllAnswers: [],
  CustomQuestions: [],
  CustomNaming: [],
  HoldItemTrigger: false,
};

export const initState = {
  User: {
    ID: 0,
    Name: "",
    Email: "",
    Image: "",
    Role: "",
    Status: "",
    "Last Login": "",
    "Account Created": "",
    Company: "",
    "Phone Number": "",
    "Email Verified": false,
  },
  AllLocations: {
    CustomMLTItmes: [],
    CommonMLTItems: [],
    Location: [],
  },
  CurrentLocation: {
    Location: 0,
    Active: 0,
    Cabinet: 0,
    Asset: 0,
    Counts: {
      Location: 0,
      Cabinet: 0,
      "Rackable Assets": 0,
      "NonRackable Assets": 0,
    },
    AllItems: {},
    HoldItem: {},
    AllAnswers: [],
    CustomQuestions: [],
    CustomNaming: [],
    HoldItemTrigger: false,
  },
  HoldLocation: BlankCurrentLocation,
  MLT: {
    rows: [],
    uniqueHeaders: {},
    sortDirection: 0,
    sortType: "",
    searchInput: {
      Object: "",
      Make: "",
      Model: "",
      Height: "",
      Width: "",
      Depth: "",
      RUHeight: "",
      Class: "",
      Subclass: "",
      Mounting: "",
      DataPortsCount: "",
      PowerPortsCount: "",
      FrontSlotsCount: "",
      BackSlotsCount: "",
    },
    filters: {
      Object: [],
      RUHeight: [],
      Make: [],
      Model: [],
      Height: [],
      Width: [],
      Depth: [],
      Class: [],
      Subclass: [],
      Mounting: [],
      DataPortsCount: [],
      PowerPortsCount: [],
      FrontSlotsCount: [],
      BackSlotsCount: [],
    },
    holdMLTItem: BlankCurrentLocation,
    checkedIndex: -1,
    OpenUP: -1,
  },
  Routing: {
    Loading: false,
    Login: 0,
    LoginModal: -1,
    CurrentPage: 0,
    AuditPage: 0,
    AuditModal: -1,
  },
};
